CREATE TABLE USER_TBL (
    ACCOUNT_NO      VARCHAR(20)  NOT NULL PRIMARY KEY,
    USERNAME        VARCHAR(50)  NOT NULL UNIQUE,
    LASTNAME        VARCHAR(50)  NOT NULL,
    FIRSTNAME       VARCHAR(50)  NOT NULL,
    EMAIL           VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR(255) NOT NULL,
    DATE_REGISTERED DATETIME     NOT NULL DEFAULT GETDATE()
);